language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    # Emulator image
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

before_install:
    # Set up sdkmanager
    - yes | sdkmanager "platforms;android-28"

before_script:    
    # Take control of gradlew file
    - chmod +x gradlew
    # Run emulator
    - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - ./gradlew connectedCheck
    - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)