version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # Take permission on gradlew
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      # Download Dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      # Save cache
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # Unit tests
      - run:
          name: Run UnitTest
          command: ./gradlew test

      # Save the Html report from the unit test step
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

      # Build APKs
      - run:
          name: Assemble APKs
          command: ./gradlew assembleAndroidTest assemble

      # Configure Google gcloud SDK
      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: Run UI Tests
          command: >-
          gcloud firebase test android run
          --type instrumentation
          --app app/build/outputs/apk/debug/app-debug.apk
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          --device model=Nexus6P,version=27,locale=en,orientation=portrait
          --device model=Nexus4,version=21,locale=en,orientation=portrait
          --timeout 30m
          no_output_timeout: 30m
# More infos : https://www.brightec.co.uk/ideas/firebase-test-lab-circleci